@host = http://localhost:3008/api/v1
### bundle
POST {{host}}/bundle
Content-Type: application/json

{
  "content": "
  import { debounce } from 'lodash';
  export get_sum = (request) => {
    const { a, b } = request.params;
    return debounce(a + b, 1000); 
  }
  "
}

### execute
POST {{host}}/bundle/execute
Content-Type: application/json

{
  "content": "export get_sum = (a, b) => { return a + b; }",
  "functionName": "get_sum",
  "params": {
    "a": 1,
    "b": 2
  }
}