@host = http://localhost:3008/api/v1
### bundle
POST {{host}}/bundle
Content-Type: application/json

{
  "content": "export get_sum = (a, b) => { return a + b; }"
}

### execute
POST {{host}}/bundle/execute
Content-Type: application/json

{
  "content": "export get_sum = (a, b) => { return a + b; }",
  "functionName": "get_sum",
  "args": [1, 2]
}